runtime: nodejs20
entrypoint: './sesamo-backend'

handlers:
  - url: /.*
    secure: always
    script: auto
instance_class: F1
automatic_scaling:
  max_instances: 1
  min_instances: 1
inbound_services:
  - warmup
