name: Deploy to Google App Engine
on:
  push:
    branches:
      - master
      - feat/rust

jobs:
  build:
    runs-on: ubuntu-latest
    name: Publish to app engine
    steps:
      - name: Checkout master
        uses: actions/checkout@v4
      - name: Restore credentials
        run: echo "${{ secrets.GCP_SA_KEY }}" | base64 -d > ./firebase_reader.json
      - name: Cache
        uses: Swatinem/rust-cache@v2
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install deps
        run: sudo apt-get update && sudo apt-get install -y musl-tools openssl libssl-dev pkg-config libudev-dev
      - name: Install MUSL target
        run: rustup target add x86_64-unknown-linux-musl
      - name: Test
        run: cargo test
        env:
          FIRESTORE_DATABASE: test
      - name: Build
        run: cargo build --target x86_64-unknown-linux-musl --release
      - name: Move binary
        run: mv ./target/x86_64-unknown-linux-musl/release/sesamo-backend ./sesamo-backend
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ilteoood/sesamo-backend
          file: ./Dockerfile-dockerhub
          context: .
      - uses: 'google-github-actions/auth@v2'
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - uses: 'google-github-actions/deploy-appengine@v2'
        with:
          project_id: ${{ secrets.PROJECT_ID }}
