name: Deploy to Google App Engine
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Publish to app engine
    steps:
      - name: Checkout master
        uses: actions/checkout@v4
      - name: Restore credentials
        run: echo "${{ secrets.GCP_SA_KEY }}" | base64 -d > ./firebase_reader.json
      - name: Cache
        uses: Swatinem/rust-cache@v2
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Build and test binary
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: both
          target: x86_64-unknown-linux-musl
          args: "--locked --release"
          strip: true
        env:
          CROSS_CONTAINER_OPTS: "-v /var/run/docker.sock:/var/run/docker.sock"
      - name: Move binary
        run: mv ./target/release/sesamo-backend ./sesamo-backend
      - uses: 'google-github-actions/auth@v2'
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - uses: 'google-github-actions/deploy-appengine@v2'
        if: github.ref == 'refs/heads/master'
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          flags: --no-cache
