name: Deploy to Google App Engine
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Publish to app engine
    steps:
      - name: Checkout master
        uses: actions/checkout@v4
      - name: Restore credentials
        run: echo "${{ secrets.GCP_SA_KEY }}" | base64 -d > ./firebase_reader.json
      - name: Cache
        uses: Swatinem/rust-cache@v2
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Test
        run: cargo test
        env:
          FIRESTORE_DATABASE: test
      - name: Build
        run: cargo build --release
      - name: Move binary
        run: mv ./target/release/sesamo-backend ./sesamo-backend
      - uses: 'google-github-actions/auth@v2'
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - uses: 'google-github-actions/deploy-appengine@v2'
        if: github.ref == 'refs/heads/master'
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          flags: --no-cache
