name: Deploy to Google App Engine
on:
  push:
    branches:
      - master
      - feat/rust

jobs:
  build:
    runs-on: ubuntu-latest
    name: Publish to app engine
    steps:
      - name: Checkout master
        uses: actions/checkout@v4
      - name: Restore credentials
        run: echo "${{ secrets.GCP_SA_KEY }}" > ./firebase_reader.json
      - name: Cache
        uses: Swatinem/rust-cache@v2
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Test
        run: ls -lah && cargo test
        env:
          FIRESTORE_DATABASE: test
      - uses: 'google-github-actions/auth@v2'
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - uses: 'google-github-actions/deploy-appengine@v2'
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          flags: --no-cache