name: Deploy to Google App Engine
on:
  push:
    branches:
      - master
      - feat/rust

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    name: Publish to app engine
    steps:
      - name: Checkout master
        uses: actions/checkout@v4
      - name: Cache
        uses: Swatinem/rust-cache@v2

      - name: Restore credentials
        run: echo "${{ secrets.GCP_SA_KEY }}" > ./firestore_reader.json
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: both
          target: x86_64-unknown-linux-musl
          args: "--locked --release"
          strip: true
        env:
          FIRESTORE_DATABASE: test
      - uses: 'google-github-actions/auth@v2'
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - uses: 'google-github-actions/deploy-appengine@v2'
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          flags: --no-cache